spring.application.name=clinica
server.port=8081

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true 
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_gestao_consultas
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


logging.level.org.hibernate.type=trace